### ISSUE TITLE
APRS digipeater

### ISSUE THREAD

**Issue by apachler** [PiInTheSky/pits#2]
It would be fine if it is possible to add a radiometrix RX1 module so that the PITS can perform as APRS digipeater ...

**Comment by Upuaut** [comment]
This is very viable but outside of the scope of the Pi In The Sky project. 

I'd use a BiM1h module http://www.radiometrix.com/content/bim1h

Its a 0.5W transceiver however the issue is you need to get the audio output into the Pi somehow. With no on board or headered microphone socket this potentially means decoding the APRS via a MX614 modem chip or something.
